//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsuCorpRound3.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IsuCorpRound3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Favorites.
        /// </summary>
        public static string ADD_TO_FAVORITES {
            get {
                return ResourceManager.GetString("ADD_TO_FAVORITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdate.
        /// </summary>
        public static string BIRTHDATE {
            get {
                return ResourceManager.GetString("BIRTHDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Alphabetic Ascending.
        /// </summary>
        public static string BY_ALPHABETIC_ASC {
            get {
                return ResourceManager.GetString("BY_ALPHABETIC_ASC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Alphabetic Descending.
        /// </summary>
        public static string BY_ALPHABETIC_DESC {
            get {
                return ResourceManager.GetString("BY_ALPHABETIC_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Date Ascending.
        /// </summary>
        public static string BY_DATE_ASC {
            get {
                return ResourceManager.GetString("BY_DATE_ASC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Date Descending.
        /// </summary>
        public static string BY_DATE_DESC {
            get {
                return ResourceManager.GetString("BY_DATE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Ranking.
        /// </summary>
        public static string BY_RATING {
            get {
                return ResourceManager.GetString("BY_RATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Type.
        /// </summary>
        public static string CONTACT_TYPE {
            get {
                return ResourceManager.GetString("CONTACT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CREATE_RESERVATION {
            get {
                return ResourceManager.GetString("CREATE_RESERVATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Reservation.
        /// </summary>
        public static string CREATE_RESERVATION_TITLE {
            get {
                return ResourceManager.GetString("CREATE_RESERVATION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DESCRIPTION {
            get {
                return ResourceManager.GetString("DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EDIT {
            get {
                return ResourceManager.GetString("EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullname.
        /// </summary>
        public static string FULLNAME {
            get {
                return ResourceManager.GetString("FULLNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PHONE_NUMBER {
            get {
                return ResourceManager.GetString("PHONE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking.
        /// </summary>
        public static string RANKING {
            get {
                return ResourceManager.GetString("RANKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation List.
        /// </summary>
        public static string RESERVATION_LIST {
            get {
                return ResourceManager.GetString("RESERVATION_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Reservation.
        /// </summary>
        public static string UPDATE_RESERVATION_TITLE {
            get {
                return ResourceManager.GetString("UPDATE_RESERVATION_TITLE", resourceCulture);
            }
        }
    }
}
