//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsuCorpRound3.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int Id { get; set; }
        public string fullname { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public string description { get; set; }
        public int ContactType_Id { get; set; }
        public string phone { get; set; }
        public Nullable<short> rating { get; set; }
        public bool is_favorite { get; set; }
    
        public virtual ContactType ContactType { get; set; }
    }
}
